language: java
before_install:
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-'uname
  -s'-'uname -m' > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
install:
- mvn install -Dmaven.javadoc.skip=true -B -V
- ls -l
- docker build --build-arg JAR_FILE=/target/backend.jar -t $DOCKER_USERNAME/se234-lab10-backend .
- docker push meandthefirefly/se234-lab10-backend
- docker push meandthefirefly/se234-lab10-client
script:
- docker-compose -H "DOCKER_HOST" up -d
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: plb2q/JVkHzaKcMocp6Ynjh7+Z2U7AfQdLesLwAnbEWjrmyx20AmxFuPiQbjcELua0F/s5Rs3dnOixR+t9pxWtp64EsB4Yh2jQmNiPS2zNlnGX8BKBuMQX3qZ9IjQt2Bt6ZIXqxtuf9ljeVSoHUBv/KMe8j9xqT5Xx4UgwvFtFCpnQwpLLIq/O/wbSErdDzLwnwdZrTpGAwoiZ2t9vb5uL/3E3/gFFD8swllkUwMPlYR2cbAYUEd//M0VhY39lkYUh2CsVtV7pr7MMG03HfaMrHj6JmZIr7bHbzZnqGDhCJUK+u+myxY2cN55ulHz0pvot4vE+VVjqYdDKCpzeQ2HFpMyvMU/IrvcQyiyCJbjiY95rwhhPOP3ysPuXhmFPnAgsYiCGj7FHSLcOqC2VdTU2RYN3q/cvidbCG0F+VumOEbc6PzcBDkSIO7sf1E86qWjzR80rfa/cwl0oZqNSzCSrcc4NEytqF47eUimX8XLqDwXG2GRlTkKR8GEH15nqlspExE+9uccDoasHSFvfanOij0Dtcpg/y/8DujVAy9DK5v+2r/mqBZ04auRLbMihpa8x0JbQt4LxrgZCDVhw+r9n3qxLv1N0B/Nk0+vNRmh4nOetP5S8AnsUI1vrjsFYvd15UdCZyA4QHy+w7qGvCo6igWA1hZpap9leDxcGY7wvc=
  - secure: ylyLOjtcvMeL4EHXdNiXu4/2WMcRERAPtMtTZ5zeFyHh6HyTqygoBHF8uVzi734aPT3dHBQiTDYmEop7fC4iiniUjlRyJy5XkevRYWuyvFP8R9UAjg6Rx9jAi1+3H/NQOq/IOkHCITS2bjcCbygCiu9dPnCqtFnb1kmCo3LjKTKrtGpKbTe24B5VHvyFh1hgEuwY75vgyUF0Wy2PBqadZ6KX2mhH+COD/V8V1G1LrKFcodcMWn9HR4u1HvgoNeSV24GnbUdpt/D4tzDen6X+tIkdVHZPzxflgXHImZ5jRQjxiU3kOotOeDEFGSQUw1budXi3zk2J5FiMrRqF+3qwS1LywpZZ3cRQ7PicGVxr4QVWKp9icNNy+QuT+LxCkrQVrQ8lvAnaDYbirniZrbSe/4Bh2irq31R78SrFYFmP+z/wR3UN2zahJGLGJT8fAoekG0CKyTUEv0szXid6ODqoybgB2RktQRdjRet0a4/n5UMn51ZhvpmUWolYNz7VqtjRypHwtZhp+cFjhhhMJW7yye0/9JGddtG/lBXCT/5DaBKftGTlxHzxGk46qgK77Z39FZl5XMVljeGaiUQDFon484UoQkGaFFEq9ygO6l9S9EAVAxVQ+hOnpGRlHd24B4CDMrgMGpYAur5Ww9H0bu/UdDWAhd+1fPTj3v+qpah0MRg=
  - secure: rb/avLrzhoCGuO4tmz3Eh4UQXnv1KEDE0cbfXjm+/O5cTTKLfy6zUORtaHKMPpn8WC3VTkelauqHdN/0zvSw6NWMBBwGyIsj9sAJrJGgpGQcqgu3OEhaVivDbZ+lze6gThcYrLH7NdxaZqhRVOU+n94ygarpjvmnG/xI8O8epdNjuGHpCHj0kRoCkWu1Zud+Gk+RYKBrriJm97KUwmHfcTLAbXB+lKq/nnhUPcGxbkOs8mhJ7qxElL/vV/16A98pil644wohk0RNZtNfzyqdwhTXACnzBxLdixziC+d9vpuNUVMZQeo2oiVhRUJczcyfG0Vm4M3j7zCAhoiqzHckQgbYiVn6dTV8HpP2qH6WMcQKErCP2Pk38yFyOCPW17lbnnxKNsOA+aqc9IA+f2z/uXYkJePt5jXwYlvWXMonXNdWVlRJFV4BKGxiZ3qVQCDEJZ9WyGyBlro11zM9PVj2KWK0yfmjXp197Ty0seNtzxVkc5xwdQkhiV+eueahOhCm+Se7VHbLBqeWsaj8vWQeFj0AvGCzJPFpuOWoeTTscuOvCHbFJTTCI1aiFVJagj4XEOnzPV2hyDOiqEmJOJovC3p6luB2seJZxPAuAmmORQlEMaf6pM2HKuLXw5LIn+j5kDmhq3qAjwYhSDmE+GbfNjQitpdmdTFnjYYGn9V35uw=
