language: java
before_install:
- sudo rm /usr/local/bin/docker-compose
- sudo curl -L https://github.com/docker/compose/releases/download/1.20.1/docker-compose-`uname
  -s`-`uname -m` -o /usr/local/bin/docker-compose
- sudo chmod +x /usr/local/bin/docker-compose
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
install:
- mvn install -Dmaven.javadoc.skip=true -B -V
- ls -l
- docker build --build-arg JAR_FILE=/target/backend.jar -t $DOCKER_USERNAME/se234-lab10-backend
  .
- docker push  $DOCKER_USERNAME/se234-lab10-backend
- docker pull  $DOCKER_USERNAME/se234-lab10-client
script:
- docker-compose -H "$DOCKER_HOST" up -d
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: sSyFN4x9lK8R/JYOk85NZQwkLme9fQiki1xms8Hv4R9ZpRWYlwAPR9ad9sRCslFpTtZqyVwg6QQojyBp/sLHfnYAFrsAcvGaG2vZTxu8ptHG9K5hotnQdS8oj5b7XtORccpNN6cDzZfqt+dlFTOQaKeD7ZlP30IoN36hHASgWxW3cD2cd8i+26cswAOkji4Qwa54kUajdATqRD9ucwwoN2bmh5IvaqlPZsQGQnv5beayQI7nwMl+okknv/KmjuBGz1WG+SZkNfQcmvfuP/JjdAhEn9Yh1bXEVFU2ZpzSsZaD3W+8G5JWFjWOzoreYWHhsI+NWxK8uB5vdvfDY9VuBi2fJPUPj+BK4GUW1u96MracI+hOOwojaUs/qH2DVVYLHQbIC56WLda9vWW29kC5kvq4wi3fVeCIzMCTDZYg9pz2tXM0SUiNuYUAJC08Sy9jVNnH8U/cTdDcJ8rT2BLnlXjcfOPz53SiT7k5CzUibrZTpyayfyP6S3w56qrYMkS1v9isBuAx/QTwEffmN39FOjThGWXb0yz9vRiycWRiDsL1N466jsroDh3f6Jk8es0qWBHPd+zPMlXlnHVSrcFUuLUb7iQOFCDpOD2S147Jlds/RGKGNfd+M2pUpG65LQMk5AAfXVhl6mzbX7uLMbrqkARzW5sJv4k35334EexCm00=
  - secure: pmhTT3tEhCjsY2/4m70QnpmO+VXtc59G9GP3ztYStdhVFiN+xKX3hjzgfA1K1pl+jpyh8KVyDUTx3cTecCN9wrJVnZW4MnGmXx43gDi8Rz8WDASgxjQ9QqAMBpXrAQzToU3ucOv0tzJmvAiGGxgf4luoyngVzsPpok4aN1z0JOlza0UJPj8va8zxwPnQ5lz5fDezDYbnyQan3VEVlboTXNvuUkeqhhOZjNwo6jpyxOILCbll8HbJJDUQoSNwHRSHZiclUMCeefdvQbQEHdgR5qsDzE4fS8VCMsx8Drvgg8uV/8Rb+ybHyMaW+xjX3bP5MbpxNdewVX3lehXpMI31LWE2C+PEi+BRY+Ypi0CN4OjohJFI/z0OF2M/PjKdbKJhZXgecuZEr0oZPSoXZOsz5K0tdKoUUHH40h7FdSNLc9/NN8s/BCie34D14PqyACZzwNGZ9tGTunh/w7dqXUX9Drduqg3AqVJeop4Idmd8T9qWn4uMNRSQwix+edWcYnq9IWufQBTK0YzlskKqYyJ+55lBq4atf/KxceaPz9+M7NTD7PL76S/7J6Ox3p/c1ldAqLNiX4oWVOfnb0GYi+UirZBTrRnknTSpjeu6IEocjVjBHKSigTWvkZr6lFBjCxoCfSrSkcGLN6A3hz/Wa1m3M/8J+91029UZnJXz6Y0TXL8=
  - secure: AyrTFDaEQdOZL978/17oLHHaBEqAqC8VxzdiySN+kQLFRpNZOsb1PMLX3lX2zoDmTc2kc84HIZskvwdoe7XqE0Wd9dC8H/0FhzK12KklQEpVl9XG7tQ+pt/UUhSCTRZHAMbrNzeeHAbYOcwzwvSWGO2DAn2syjOxGnpFBuuBQynxE9n6LDoGi/tc84WC5Y0ZDrS2cTHDYi1+ZZuBiN+qK1F8NiS3Wus9ShQuwDrp4ZXEsif4jgW+Lya+Vu3j6bvSP5T2seXIFMH7l2uZ+zeHTVlWkDjAP9XtTQFI8WAN6ebqoguRJ1PzN2IxrgbMEL8U1ucBY8L/jNKjKLj0/0EeooeOnCWB+nZj+OKoJL6j7b/AwK2EHWloRfkmnFrSqxhBJhNTVlmtCX5QpQp/cUIH8r+50EkFDahQJtxrDuv9s1YRpbJGuKZWo0+UFRzqKPvAklkrby90FyNMIFFKjgdkGy216SptunmzymcvzvLQ3TLWyZNCGPi7yh95wYyWJKZEC+smPeI90Rr4J6Pl6sbZsk8dXiYXwMpqKl2qUKt+SiLjojYYjI11GukrAuylL7SyY/wHbckfb4sZe4vAYgp/6oX5DAXrCkssyVj63MgF8pKcj06GWcl6NpPO7DqK5MHxEpWZLCU/xiPQVCC9glPy3zKG+PqOUMpk2v2KgxPWhuM=
